config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  post '/admin/catering_orders/cancel_order', to: 'admin/catering_orders#cancel_order', as: :admin_cancel_catering_order
  ActiveAdmin.routes(self)
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  root 'dashboard#catering'
  get 'phone', to: 'users#new', as: :signup_phone
  get 'verify', to: 'users#new', as: :signup_verify
  get 'profile', to: 'users#new', as: :signup_profile
  get 'location', to: 'users#new', as: :signup_location
  get 'new_apartment', to: 'users#no_apartment_found', as: :no_apartment_found
  get 'order_payment/:url_safe_token', to: 'users#order_payment', as: :order_payment

  post 'register_payment', to: 'users#register_payment', as: :register_payment
  get 'users/:id(.:format)', to: 'users#show', as: :user

  get 'thanks', to: 'users#thankyou', as: :thankyou
  get 'cc_complete', to: 'users#cc_complete', as: :cc_thankyou

  post 'api/v1/text_response', to: 'api/v1/text_response#receive'
  
  get 'orders', to: 'catering_orders#index'
  get 'orders/:id(.:format)', to: 'catering_orders#show', as: :catering_order
  post 'orders/cancel_order', to: 'catering_orders#cancel_order', as: :cancel_catering_order
  post 'orders/cancel_request', to: 'catering_orders#cancel_request', as: :cancel_catering_order_request
  get 'dashboard', to: 'dashboard#catering', as: :dashboard
  get 'dashboard/order_complete', to: 'dashboard#order_complete'
  get 'dashboard/order_history', to: 'dashboard#order_history'
  get 'newsletter_subscribers', to: 'dashboard#catering'
  post 'newsletter_subscribers', to: 'dashboard#create_newsletter_subscriber'
  post 'dashboard/update_filter_selections', to: 'dashboard#update_filter_selections'
  post 'dashboard/edit_catering_item', to: 'dashboard#edit_catering_item'
  post 'dashboard/check_payment_source', to: 'dashboard#check_payment_source'
  post 'dashboard/check_dish_minimum', to: 'dashboard#check_dish_minimum'
  post 'dashboard/bulk_update_catering_dishes', to: 'dashboard#bulk_update_catering_dishes'
  post 'dashboard/preauth_payment', to: 'dashboard#preauth_payment'
  post 'dashboard/place_catering_order', to: 'dashboard#place_catering_order'
  post 'dashboard/update_sms_number', to: 'dashboard#update_sms_number'
  post 'dashboard/reset_password', to: 'dashboard#reset_password'
  delete 'dashboard/delete_catering_dish', to: 'dashboard#delete_catering_dish'

  post 'dashboard/sign_up', to: 'dashboard_users#sign_up'
  post 'dashboard/login', to:'dashboard_users#login'
  get 'signup', to:'dashboard_users#new'
  get 'login', to:'dashboard_users#new_session'
  patch 'users/:id', to:'dashboard_users#update'

  get 'm/:url_safe_token', to: 'menus#show', as: :menu_image_redirect

  get ':slug', to: 'dashboard#catering', as: :restaurant
  resources 'pairings'

end

app/models/pairing.rb
class Pairing < ActiveRecord::Base
  has_many :restaurants
  accepts_nested_attributes_for :restaurants, allow_destroy: true
end

app/views/modals/_banner_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="bannerModal" data-backdrop="static">
  <div class="modal-dialog modalbanner" role="document" style="min-width:800px;z-index: 4555">
    <div class="modal-content modalbanner-content">
      <div class="modal-header modalbanner-header">
        <button type="button" class="modal-close-white close" data-dismiss="modal" aria-label="Close" style="top: -32px;right: -69px;"><span aria-hidden="true">&times;</span></button>
        <div style="font-family: GothamLight;line-height: 137px;font-size: 24px" class="modalbanner-title">
          <%= image_tag '001logo.png', :width => '150px', :height => '130px', :style => 'filter: brightness(50%) sepia(100%) saturate(10000%) hue-rotate(255deg)' %>
        </div>
        <div style="display: block;padding-top: 30px;letter-spacing: 0.02em;"><h1 style="margin-bottom: 4px">Summer Savings!</h1></div>
<!--        <h3 class="modal-title modalbanner-title">banner</h3>-->
      </div>
      <div class="modal-body modalbanner-body" style="flex-direction: column;display: flex">
        <div style="font-size: 24px; line-height: 32px">
          We're delivering Vancouver's best food to your office teams for free. All summer long.
        </div>
        <div><hr style="height:4px;width:110px;float:left;margin-top:25px;background-color:#5951ff;"></div>
        <div style="font-size: 24px; font-family: GothamLight;margin-top: 22px;line-height: 32px">Save $20 on delivery from 1 or 2 restaurants until August 30, 2020. No promo code at checkout required.</div>
      </div>
    </div>
  </div>
</div>

app/views/modals/_card_select_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="cardSelectModal" data-backdrop="static">
  <div class="modal-dialog modalcard" role="document" >
    <div class="modal-content modalcard-content">
<!--      <button type="button" class="modal-back close" id="cardGoBack" aria-label="Go Back" style="top: -71px;left: -9px;">←<span aria-hidden="true"> Go back</span></button>-->
      <button type="button" class="modal-back close" id="cardGoBack" aria-label="Go Back" style="top: 13px;left: 21px;">←<span aria-hidden="true"> Go back</span></button>
      <div class="modal-header modalcard-header">
        <h3 class="modal-title modalcard-title">Payment Method</h3>
      </div>
      <div class="modal-body modalcard-body">
        <form class="needs-validation cardform" id="card-form" novalidate>
          <div class="modal-section">
            <div class="modalcard-subtitle">
              <%= @brand %>
              Visa, Mastercard and American Express are accepted payment methods. If you'd like to pay via direct deposit, please click <a href="#" id="skipOrder" style="color: #5951ff">here</a>
            </div>
          </div>
          <div class="form-group col-md-12">
              <div id="saved-card">
                <div class="col-lg-2">
                  <%=image_tag("check.svg", class: "modalcard-check_icon", :alt => "Icon Check")%>
                </div>
                <div class="col-lg-7 card-id">
                  <%# Stripe::Customer.retrieve(current_user.stripe_token).sources %>
                  <% current_user = @current_user %>
                  <% current_user&.stripe_token&.present? ? cus = Stripe::Customer.retrieve(current_user.stripe_token).sources.data[0] : "test" %>
                  <span id="cardBrand"><% if cus %><%= cus.brand %><% end %></span> **** <span id="cardLast4"><% if cus %><%= cus.last4 %><% end %></span>
                </div>
                <div class="col-lg-3">
                  <span id="cardExpMonth"><% if cus %><%= cus.exp_month %><% end %></span>/<span id="cardExpYear"><% if cus %><%= cus.exp_year.to_s[-2..-1].to_i %><% end %></span>
                </div>
              </div>
            <div id="new-cc">
              <button type="button" id="addCard" class="btn btn-outline-primary modalcard-button-signup" data-persist="date">Add a different card</button>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer modalcard-footer">
        <div class="btn-group-justified btn-group-vertical modalcard-button_group">
          <button type="submit" id="cardSubmit" class="btn btn-primary modalcard-button_signup" data-persist="date">Place Order</button>
          <div class="modalcard-footer-subtitle">
            <i class="fa fa-lock fa-xs" aria-hidden="true"></i>This is a secure transaction.
          </div>
        </div>
        
      </div>
      <div id="hiddenField" data-restaurant-id="" data-dish-id="" style="visibility: hidden"></div>
    </div>
  </div>
</div>

app/views/modals/_datepicker_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="cateringDatePicker" data-backdrop="static">
  <div class="modal-dialog modaldatepicker" role="document" >
    <div class="modal-content modaldatepicker-content">
      <button type="button" class="modal-close-purple close" data-dismiss="modal" aria-label="Close" style="top: -50px;right: -129px;"><span aria-hidden="true">&times;</span></button>
      <div class="modaldatepicker-title">
        <span class="modal-title">Set your delivery date</span>
      </div>
      <div class="modaldatepicker-subtitle">We require 2 days of advanced notice</div>
      <div class="modal-body modaldatepicker-body">
        <%= render "modules/datepicker" %>
      </div>
      <div class="modal-footer modaldatepicker-footer">
        <div class="btn-group-justified btn-group-vertical modaldatepicker-button_group">
<!--          <button type="button" class="btn modaldatepicker-button_cancel" data-dismiss="modal">cancel</button>-->
          <button type="button" class="btn btn-primary modaldatepicker-button_update" data-persist="date">Update</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/modals/_dish_minimum_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="dishMinimum" data-backdrop="static">
  <div class="modal-dialog modaldishminimum" role="document" >
    <div class="modal-content modaldishminimum-content">
      <button type="button" class="modal-close close" data-dismiss="modal" aria-label="Close" style="top: 0px;right: 64px;"><span aria-hidden="true">&times;</span></button>
      <div class="modal-header modaldishminimum-header">
        <div class="modal-title modaldishminimum-title">Oops!</div>
      </div>
      <div class="modal-body modaldishminimum-body">
        <form class="needs-validation modaldishminimum-form" id="dishminimum-form" novalidate>
          <div class="modal-section">
            <div class="modaldishminimum-subtitle">
              <% if @catering_order&.subselections.present?%>
                <% restaurant_ids = [] %>
                <% @catering_order.subselections.each do |sub| %>
                  <% restaurant_ids << sub.dish.restaurant_id %>
                <% end %>
                <% restaurant_ids = restaurant_ids.uniq %>
                <% restaurants = Restaurant.find(restaurant_ids.sort) %>
                  <span id="minimum-text-1" rest-id=<%=restaurants.first.name %>>
<!--                    Your order can't proceed because <span id="mdr1"><%#= restaurants.first.name %></span> requires a <strong style="font-weight:900">minimum of <span id="min1"><%#= restaurants.first.min_quantity %></span> dishes.</strong>-->
<!--                    Add <span id="quant1"><%#= restaurants.first.min_quantity %></span> more dishes from <span id="mdr2"><%#= restaurants.first.name %></span> to place your order or simply remove them-->

                    <span id="mdr1"><%= restaurants.first.name %></span> requires a <strong style="font-weight:900">minimum of <span id="min1"><%= restaurants.first.min_quantity %></span> dishes.</strong> Add <span id="quant1"><%= restaurants.first.min_quantity %></span> more dishes from <span id="mdr1"><%= restaurants.first.name %></span> to place your order. If you change your mind, you can remove the dish(es)."
                  </span>
                <% if restaurants.count >= 2 %>
                  <br><br>
                  <span id="minimum-text-2" rest-id=<%= restaurants.last.name %>>
<!--                    Your order can't proceed because <span id="mdr3"><%#= restaurants.last.name %></span> requires a <strong style="font-weight:900">minimum of <span id="min2"><%#= restaurants.last.min_quantity %></span> dishes.</strong>-->
<!--                    Add <span id="quant2"><%#= restaurants.last.min_quantity %></span> more dishes from <span id="mdr4"><%#= restaurants.last.name %></span> to place your order or simply remove them-->

                    <span id="mdr3"><%= restaurants.last.name %></span> requires a <strong style="font-weight:900">minimum of <span id="min2"><%= restaurants.last.min_quantity %></span> dishes.</strong> Add <span id="quant2"><%= restaurants.last.min_quantity %></span> more dishes from <span id="mdr3"><%= restaurants.last.name %></span> to place your order. If you change your mind, you can remove the dish(es)."
                  </span>
                <% end %>
              <% end %>
            </div>
          </div>

        </form>
      </div>
      <div class="btn-group-justified btn-group-vertical modaldishminimum-button_group">
        <%# link_to :back do %>
          <button type="submit" id="dishminimumSubmit" data-dismiss="modal" aria-label="Close" class="btn btn-outline-primary modalcard-button-signup" data-persist="date">Contact Support</button>
        <%# end %>
        <%# link_to :back do %>
          <button type="submit" id="dishminimumSubmit" data-dismiss="modal" aria-label="Close" class="btn btn-primary modalcard-button-signup" data-persist="date">Got It</button>
        <%# end %>
      </div>
      <div id="hiddenField" data-restaurant-id="" data-dish-id="" style="visibility: hidden"></div>
    </div>
  </div>
</div>

app/views/modals/_dish_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="dishModal" data-backdrop="static">
  <div style="width: 100% !important;
      max-width: 614px !important;
      margin: auto;
      position: relative;
      ">
    <button type="button" class="modal-close-white close" data-dismiss="modal" aria-label="Close" style="top:0px;right:-80px;"><span aria-hidden="true">&times;</span></button>
  </div>

  <div class="modal-dialog modaldishpicker" role="document" >
    <div class="modal-content modaldishpicker-content">
<!--      <button type="button" class="modal-close close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>-->
      <div class="modal-body modaldishpicker-body">
        <div class="card mx-auto dishcardmodal">
          <img class="card-img-top dishcardmodal_image" src="" alt="Card image cap">
          <div class="card-body dishcardmodal_body">
            <div class="dishcardmodal_container">
              <div class="row">
              <div class="col-sm-9">
                <h5 class="card-title dishcardmodal_title">
                  Placeholder
                </h5>
              </div>
<!--              <div class="col-sm-3">-->
<!--                <h5 class="card-title dishcardmodal_price">-->
<!--                  $10-->
<!--                </h5>-->
<!--              </div>-->
            </div>
              <p class="card-text dishcardmodal_text">
                Placeholder
              </p>
<!--              <div class="dishcardmodal_badge-container">-->
<!--                <span class="badge badge-primary dishcardmodal_badge dishcardmodal_badge_meat">MEAT</span>-->
<!--                <span class="badge badge-primary dishcardmodal_dietarycircle">GF</span>-->
<!--              </div>-->
              <div class="dishcardmodal_subselection">
              </div>
              <div class="card row subcardnotes">
                <div class="row" style="margin:0;">
                  <div style="width:100%;">
<!--                    <input class="dishcardmodal-notes" maxlength="60" type="text" placeholder="Add special instructions (optional)">-->
                    <textarea class="dishcardmodal-notes" maxlength="60" type="text" placeholder="Add special instructions (optional)" rows="2"></textarea>
                  </div>
                </div>
              </div>
            </div>

          </div>
          <div style="width:100%;height:2px;position: absolute;"></div>
        </div>
        <div class="modal-footer modaldishpicker-footer">
          <div class="btn-group-justified btn-group-vertical modaldishpicker-button_group">
            <%= link_to dashboard_path, id: 'modalUpdateLink' do %>
              <button type="button" id="addToOrder" class="btn btn-primary modaldishpicker-button_update noselect" data-persist="date">Add to Order</button>
            <% end %>
          </div>
        </div>
      </div>
<!--      <div class="modal-section modaldishpicker-quantity">-->
<!--        <form class="form-inline modaldishpicker-form" id="dishCounter" data-dish-counter="">-->
<!--          <input type="text" class="form-control modaldishpicker-form_special" id="specialInfo" placeholder="Add Special Instructions">-->

<!--          <span class="modaldishpicker-quantity_minus">-</span>-->
<!--          <input type="number" class="form-control modaldishpicker-quantity_count" id="dishQuantity" name="qty" value="1">-->
<!--          <span class="modaldishpicker-quantity_plus">+</span>-->
<!--        </form>-->
<!--      </div>-->

      <div id="hiddenField" data-restaurant-id="" data-dish-id="" style="visibility: hidden"></div>
    </div>
  </div>
</div>

app/views/modals/_dish_none_added_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="dishNone" data-backdrop="static">
  <div class="modal-dialog modaldishminimum" role="document" >
    <div class="modal-content modaldishminimum-content">
      <button type="button" class="modal-close close" id="dishNoneClose" aria-label="Close" style="top: 0px;right: 64px;"><span aria-hidden="true">&times;</span></button>
      <div class="modal-header modaldishminimum-header">
        <div class="modal-title modaldishminimum-title">Oops!</div>
      </div>
      <div class="modal-body modaldishminimum-body">
        <form class="needs-validation modaldishminimum-form" id="dishnone-form" novalidate>
          <div class="modal-section">
            <div class="modaldishminimum-subtitle">
              <span>
                  It looks like you didn't select any dishes to add.
              </span>
            </div>
          </div>
        </form>
      </div>
      <div class="btn-group-justified btn-group-vertical modaldishminimum-button_group">
        <%= link_to :back do %>
          <button type="submit" id="dishnoneconSubmit" class="btn btn-outline-primary modalcard-button-signup" data-persist="date">Contact Support</button>
        <% end %>
        <%= link_to :back do %>
          <button type="submit" id="dishnoneSubmit" class="btn btn-primary modalcard-button-signup" data-persist="date">Got It</button>
        <% end %>
      </div>
      <div id="hiddenField" data-restaurant-id="" data-dish-id="" style="visibility: hidden"></div>
    </div>
  </div>
</div>

app/views/modals/_loader_modal.html.erb
<div class="" tabindex="-1" role="dialog" id="loaderModal" data-backdrop="static">
  <div class="modal-dialog modaldishminimum" role="document" style="height: 90vh;display: flex">
    <div class="modal-content " style="align-items: center; border: none;justify-content: center;background-color: #00000000">
      <div class="fda-spinner">
        <%= image_tag '001logo.png', :width => '100px', :height => '100px' %>
      </div>
    </div>
  </div>
</div>

app/views/modals/_order_complete_modal.html.erb
<div class="modal" role="dialog" id="orderCompleteModal" data-backdrop="static">
  <div class="modal-dialog modalordercomplete" role="document" >
    <div class="modal-content modalordercomplete-content">
      <button type="button" id="endFlow" class="modal-close close" aria-label="Close" style="top: -40px;right: 64px;"><span aria-hidden="true">&times;</span></button>
      <div class="modalordercomplete-content_header_icon">
        <%= image_tag("icon_thumb_v1.svg") %>
      </div>
      <div class="modalordercomplete-content_header">
        Your order has been placed!
      </div>
      <div class="modalordercomplete-content_details">
        <% if current_user.present? && @catering_order.present? %>
          We'll send a confirmation email to <strong style="color: #5951ff"><%= current_user.email %></strong> when we've received
          <% restaurant_ids = [] %>
          <% @catering_order.subselections.each do |sub| %>
            <% restaurant_ids << sub.dish.restaurant_id %>
          <% end %>
          <% restaurant_ids = restaurant_ids.uniq %>
          <% if restaurant_ids.count < 2 %>
            an order confirmation from
            <%= Restaurant.find(restaurant_ids).first.name unless restaurant_ids.count < 1 %>.
          <% else %>
            order confirmations from
            <%= Restaurant.find(restaurant_ids).first.name %> and
            <%= Restaurant.find(restaurant_ids).last.name %>.
          <% end %>
        <% end %>
      </div>
      <div><hr style="height:4px;width:110px;margin-top:73px;background-color:#2fc2a2;"></div>
      <div class="modalordercomplete-content_sms">
        <%= image_tag("phone_sms_notifications_v2.svg") %>
        <div class="modalordercomplete-content_sms-title">
          Want delivery updates?

          <div id="smssub1" class="modalordercomplete-content_sms-details">
            Enter a number below and we'll text you when your food is on the way.
          </div>
          <div id="smssub2" class="modalordercomplete-content_sms-details" style="display: none">
<!--            Great! you're now subscribed for SMS delivery updates.-->
            You have successfully subscribed to delivery updates <span id="smssubtarget"></span>.
          </div>
          <input type="text" class="form-control mt-2" id="inputSms" placeholder=" " style="width: 336px;box-shadow: 0px 0px 8px 1px #ccc;margin-top: 25px !important;">
          <button type="submit" id="continueSmsSubmit" class="btn btn-primary modalordercomplete-content_sms-button" data-persist="date">
            Submit
          </button>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/modals/_payment_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="paymentModal" data-backdrop="static">
  <div class="modal-dialog modalpayment" role="document" >
    <div class="modal-content modalpayment-content">
<!--      <button type="button" class="modal-back close" id="paymentGoBack" aria-label="Go Back" style="top: -71px;left: -8px;">←<span aria-hidden="true"> Go back</span></button>-->
      <button type="button" class="modal-back close" id="paymentGoBack" aria-label="Go Back" style="top: 13px;left: 21px;">←<span aria-hidden="true"> Go back</span></button>
      <div class="modal-header modalpayment-header">
        <h3 class="modal-title modalpayment-title">Add a Card</h3>
      </div>
      <div class="modal-body modalpayment-body">
        <form class="needs-validation paymentform" id="payment-form" novalidate>
          <div class="modal-section">
            <div class="modalpayment-subtitle">
              Visa, Mastercard and American Express are accepted payment methods. If you'd like to pay via direct deposit, please click <a href="#" id="skipOrder" style="color: #5951ff">here</a>
            </div>
          </div>
          <div class="form-group col-md-12">
            <label for="inputPassword4">Name on Card</label>
            <div id="cc-payment-name">
              <input type="text" class="form-control" placeholder="Name on Card" required>
              <div class="invalid-feedback">
                Cannot be blank.
              </div>
            </div>
          </div>
          <div class="form-group col-md-12">
            <label for="card-element">
              Credit or Debit card
            </label>
            <div id="card-element">
              <!-- A Stripe Element will be inserted here. -->
            </div>
            <div id="card-errors" role="alert"></div>
          </div>
        </form>
      </div>
      <div class="modal-footer modalpayment-footer">
        <div class="btn-group-justified btn-group-vertical modalpayment-button_group">
          <button type="submit" id="paymentSubmit" class="btn btn-primary modalpayment-button_signup" data-persist="date">Add Card</button>
        </div>
      </div>
      <div id="hiddenField" data-restaurant-id="" data-dish-id="" style="visibility: hidden"></div>
    </div>
  </div>
</div>

app/views/modals/_reset_password_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="resetPasswordModal" data-backdrop="static">
  <div class="modal-dialog modallogin" role="document" >
    <div class="modal-content modallogin-content">
      <button type="button" class="modal-close close" data-dismiss="modal" aria-label="Close" style="top: -103px;right: -93px;"><span aria-hidden="true">&times;</span></button>
<!--      <button type="button" class="modal-back close" id="resetPassBack" aria-label="Close" style="top: 32px;left: 56px;font-size: 60px">←</button>-->
      <div class="modal-header modallogin-header">
        <h5 class="modal-title modallogin-title">Reset Your Password</h5>
      </div>
      <div class="modal-body modallogin-body">
        <form class="needs-validation form-inline loginform" novalidate>
          <div class="form-group row" style="width:100%;margin-left:0;margin-bottom: 50px">
            <div class="col-md-3 modal-label"><label style="justify-content: end" for="inputEmail">Email</label></div>
            <div class="col-md-9"><input type="text" class="modallogin-form-field form-control" id="resetInputPassword" placeholder=" " required></div>
            <div class="invalid-feedback invalid-user">
              Cannot be blank.
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer modallogin-footer">
        <div class="btn-group-justified btn-group-vertical modallogin-button_group">
          <button type="submit" id="resetSubmit" class="btn btn-primary modallogin-button_signup noselect" data-persist="date">Reset my password</button>
        </div>
      </div>
      <div id="hiddenField" data-restaurant-id="" data-dish-id="" style="visibility: hidden"></div>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">

</script>

app/views/modals/_reset_pw_confirm_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="resetPassConfirmModal" data-backdrop="static">
  <div class="modal-dialog modallogin" role="document" >
    <div class="modal-content modallogin-content">
      <button type="button" class="modal-close close" data-dismiss="modal" aria-label="Close" style="top: -103px;right: -93px;"><span aria-hidden="true">&times;</span></button>
<!--      <button type="button" class="modal-back close" id="resetPassBack" aria-label="Close" style="top: 32px;left: 56px;font-size: 60px">←</button>-->
      <div class="modal-header modallogin-header">
        <h2 class="modal-title modallogin-title">Check your inbox</h2>
      </div>
      <div class="modal-body modaldishminimum-body" style="flex-direction: column;display: flex;max-height:120px">
        <div>
          We emailed <span id="resetPassEmail"></span> with instructions to reset your password.
        </div>
<!--        <div><hr style="height:4px;width:110px;float:left;margin-top:25px;background-color:#90D7FF;"></div>-->
<!--        <div style="font-size: 24px; font-family: GothamLight;margin-top: 22px;line-height: 32px">To celebrate our launch, we're offering $0 delivery on every order from now until March 1.</div>-->
      </div>
      <div class="modal-footer modallogin-footer">
        <div class="btn-group-justified btn-group-vertical modallogin-button_group">
          <button type="submit" id="resetBack" class="btn btn-primary modallogin-button_signup noselect" data-persist="date">Back to log in</button>
        </div>
      </div>
      <div id="hiddenField" data-restaurant-id="" data-dish-id="" style="visibility: hidden"></div>
    </div>
  </div>
</div>

app/views/modals/_restaurant_closed_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="restaurantClosedModal" data-backdrop="static">
  <div class="modal-dialog modaldishminimum" role="document" >
    <div class="modal-content modaldishminimum-content">
      <button type="button" class="modal-close close" data-dismiss="modal" aria-label="Close" style="top: -216px;right: 64px;"><span aria-hidden="true">&times;</span></button>
      <div class="modal-header modaldishminimum-header">
        <div class="modal-title modaldishminimum-title">Oops!</div>
      </div>
      <div class="modal-body modaldishminimum-body">
        <form class="needs-validation modaldishminimum-form" novalidate>
          <div class="modal-section">
            <div class="modaldishminimum-subtitle">
                <span id="minimum-text-3">
                  This restaurant is currently unavailable to order from. Please check back later.
                </span>
            </div>
          </div>

        </form>
      </div>
      <div class="btn-group-justified btn-group-vertical modaldishminimum-button_group">
        <%= link_to :back do %>
          <button type="submit" id="dishminimumSubmit" class="btn btn-outline-primary modalcard-button-signup" data-persist="date">Contact Support</button>
        <% end %>
        <%= link_to :back do %>
          <button type="submit" id="dishminimumSubmit" class="btn btn-primary modalcard-button-signup" data-persist="date">Go Back</button>
        <% end %>
      </div>
      <div id="hiddenField" data-restaurant-id="" data-dish-id="" style="visibility: hidden"></div>
    </div>
  </div>
</div>

app/views/modals/_too_many_restaurants_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="tooManyRestos" data-backdrop="static">
  <div class="modal-dialog modaldishminimum" role="document" >
    <div class="modal-content modaldishminimum-content">
      <button type="button" class="modal-close close" id="tooManyClose" aria-label="Close" style="top: 0px;right: 64px;"><span aria-hidden="true">&times;</span></button>
      <div class="modal-header modaldishminimum-header">
        <div class="modal-title modaldishminimum-title">Oops!</div>
      </div>
      <div class="modal-body modaldishminimum-body">
        <form class="needs-validation modaldishminimum-form" id="dishnone-form" novalidate>
          <div class="modal-section">
            <div class="modaldishminimum-subtitle">
              <span>
                You have already added dishes from two restaurants. If you'd like to add dishes from this restaurant, you have to remove <em>all</em> the dishes from one of the restaurants you've selected.
              </span>
            </div>
          </div>
        </form>
      </div>
      <div class="btn-group-justified btn-group-vertical modaldishminimum-button_group">
        <%= link_to :back do %>
          <button type="submit" id="toomanyconSubmit" class="btn btn-outline-primary modalcard-button-signup" data-persist="date">Contact Support</button>
        <% end %>
        <%= link_to :back do %>
          <button type="submit" id="toomanySubmit" class="btn btn-primary modalcard-button-signup" data-persist="date">Got It</button>
        <% end %>
      </div>
      <div id="hiddenField" data-restaurant-id="" data-dish-id="" style="visibility: hidden"></div>
    </div>
  </div>
</div>