config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  post '/admin/catering_orders/cancel_order', to: 'admin/catering_orders#cancel_order', as: :admin_cancel_catering_order
  ActiveAdmin.routes(self)
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  root 'dashboard#catering'
  get 'phone', to: 'users#new', as: :signup_phone
  get 'verify', to: 'users#new', as: :signup_verify
  get 'profile', to: 'users#new', as: :signup_profile
  get 'location', to: 'users#new', as: :signup_location
  get 'new_apartment', to: 'users#no_apartment_found', as: :no_apartment_found
  get 'order_payment/:url_safe_token', to: 'users#order_payment', as: :order_payment

  post 'register_payment', to: 'users#register_payment', as: :register_payment
  get 'users/:id(.:format)', to: 'users#show', as: :user

  get 'thanks', to: 'users#thankyou', as: :thankyou
  get 'cc_complete', to: 'users#cc_complete', as: :cc_thankyou

  post 'api/v1/text_response', to: 'api/v1/text_response#receive'
  
  get 'orders', to: 'catering_orders#index'
  get 'orders/:id(.:format)', to: 'catering_orders#show', as: :catering_order
  post 'orders/cancel_order', to: 'catering_orders#cancel_order', as: :cancel_catering_order
  post 'orders/cancel_request', to: 'catering_orders#cancel_request', as: :cancel_catering_order_request
  get 'dashboard', to: 'dashboard#catering', as: :dashboard
  get 'dashboard/order_complete', to: 'dashboard#order_complete'
  get 'dashboard/order_history', to: 'dashboard#order_history'
  get 'newsletter_subscribers', to: 'dashboard#catering'
  post 'newsletter_subscribers', to: 'dashboard#create_newsletter_subscriber'
  post 'dashboard/update_filter_selections', to: 'dashboard#update_filter_selections'
  post 'dashboard/edit_catering_item', to: 'dashboard#edit_catering_item'
  post 'dashboard/check_payment_source', to: 'dashboard#check_payment_source'
  post 'dashboard/check_dish_minimum', to: 'dashboard#check_dish_minimum'
  post 'dashboard/bulk_update_catering_dishes', to: 'dashboard#bulk_update_catering_dishes'
  post 'dashboard/preauth_payment', to: 'dashboard#preauth_payment'
  post 'dashboard/place_catering_order', to: 'dashboard#place_catering_order'
  post 'dashboard/update_sms_number', to: 'dashboard#update_sms_number'
  post 'dashboard/reset_password', to: 'dashboard#reset_password'
  delete 'dashboard/delete_catering_dish', to: 'dashboard#delete_catering_dish'

  post 'dashboard/sign_up', to: 'dashboard_users#sign_up'
  post 'dashboard/login', to:'dashboard_users#login'
  get 'signup', to:'dashboard_users#new'
  get 'login', to:'dashboard_users#new_session'
  patch 'users/:id', to:'dashboard_users#update'

  get 'm/:url_safe_token', to: 'menus#show', as: :menu_image_redirect

  get ':slug', to: 'dashboard#catering', as: :restaurant
  resources 'pairings'

end

app/models/catering_order.rb
class CateringOrder < ActiveRecord::Base
  
  def self.ransackable_associations(auth_object = nil)
    ["catering_dishes", "catering_drivers", "catering_items", "catering_restaurants", "dishes", "drivers", "office", "restaurants", "subselections", "user"]
  end
  def self.ransackable_attributes(auth_object = nil)
    ["address", "cancelled_at", "charge", "charge_id", "created_at", "delivery_date", "delivery_time", "first_delivery_reminder", "id", "notify_driver", "office_id", "order_type", "preauthorized", "sms_number", "status", "stripe_invoice_id", "subscribed", "total_price", "updated_at", "user_id"]
  end

  belongs_to :office, optional: true # TO BE DEPRECATED
  belongs_to :user, optional: true # maybe remove optional true if possible

  has_many :catering_items # TO BE DEPRECATED

  has_many :catering_dishes
  has_many :dishes, through: :catering_dishes
  has_many :subselections, through: :catering_dishes

  has_many :catering_drivers
  has_many :drivers, through: :catering_drivers, dependent: :destroy

  has_many :catering_restaurants # TO BE DEPRECATED
  has_many :restaurants, through: :catering_restaurants, dependent: :destroy #TO BE DEPRECATED

  accepts_nested_attributes_for :catering_dishes, :allow_destroy => true
  accepts_nested_attributes_for :catering_items, :allow_destroy => true
  accepts_nested_attributes_for :office, :allow_destroy => true
  accepts_nested_attributes_for :restaurants, :allow_destroy => true
  accepts_nested_attributes_for :catering_restaurants, :allow_destroy => true

  STATUSES = %w[pending flagged needs_payment confirmed_needsdriver confirmed_ready picked_up arrived complete cancellation_requested cancelled]
  ORDER_TYPES = %w[admin team manual]

  DELIVERY_TIME = {
    1 => "12:00 PM - 12:15 PM",
    2 => "12:15 PM - 12:30 PM",
    3 => "12:30 PM - 12:45 PM",
    4 => "12:45 PM - 1:00 PM",
    5 => "1:00 PM - 1:15 PM",
    6 => "1:15 PM - 1:30 PM"
  }
  after_create :send_initial_notification

  def confirm_office_order
    if catering_restaurants.present?
      restaurants = Restaurant.find(catering_restaurants.pluck(:restaurant_id).uniq)
    else
      restaurants = Restaurant.find(subselections.pluck(:restaurant_id).uniq)
    end

    restaurants_text = " #{restaurants.first.name}"
    if restaurants.length > 1
      restaurants_text << " and #{restaurants.last.name}"
    end

    message = "You've been successfully subscribed to receive delivery updates for your order on #{delivery_date.strftime("%A, %B %d %Y")} - #{delivery_time.strip} at #{user.office_address} from" + restaurants_text + "."

    send_message(sms_number, message)
  end

  def send_initial_notification#(catering_items, catering_office, catering_restaurants)
    puts "DRIVER SMS TEST 1"
    if drivers.present? && !notify_driver
      puts "DRIVER SMS TEST 2"
      message = "Hey #{drivers.first.name}, you have a delivery scheduled on #{delivery_date.strftime("%A, %B %d %Y")}\n\n"

      scheduled_time = "Delivery Time: #{delivery_time.strip}\n\n"

      restaurants_text = "Restaurants:\n"
      if catering_restaurants.present?
        restaurants = Restaurant.find(catering_restaurants.pluck(:restaurant_id).uniq)
      else
        restaurants = Restaurant.find(subselections.pluck(:restaurant_id).uniq)
      end
      restaurants.each { |r| restaurants_text << "#{r.name}\nPick Up Time: #{catering_restaurants.find_by(restaurant_id: r.id).pickup_time}\nBags: #{catering_restaurants.find_by(restaurant_id: r.id).number_of_bags}\n\n" }

      catering_dishes_text = "Food to pickup:\n"
      catering_dishes.each { |cd| catering_dishes_text << "Dish: #{cd.dish.name} x #{cd.quantity}\n\n"}

      catering_office = "Office Delivery Address:\n#{user.office_name}\n#{user.office_address}\n\n"
      catering_contact = "If you have any issues entering the office, please contact the office admin, #{user.full_name}\n\n"# add in user phone eventually at #{user.phone}.\n\n"

      contact_help = "Any restaurant or delivery related issues, contact an admin"

      [scheduled_time, restaurants_text, catering_dishes_text, catering_office, catering_contact, contact_help].each { |m| message << m}
      send_message(drivers.first.phone, message)
    end
  end

  def send_driver_follow_up
    driver_message = ""
    message = "Hey #{drivers.first.name}! Friendly reminder that you have a delivery scheduled today at #{delivery_time}\n\n"
    help = "To confirm that you are able to fulfill this delivery, please text back YES or NO within 60 minutes."
    [message, help].each { |m| driver_message << m}
    send_message(drivers.first.phone, driver_message)
  end

  def confirm_catering(message)
    message = message.downcase
    if (message == "yes") # YES CAN DELIVER

      if catering_restaurants.present?
        restaurants = Restaurant.find(catering_restaurants.pluck(:restaurant_id).uniq)
      else
        restaurants = Restaurant.find(subselections.pluck(:restaurant_id).uniq)
      end
      
      if restaurants.count >= 2
        driver_text = "Thanks for confirming your availability. For today's delivery, you'll be picking up from:\n
           #{restaurants.first.name} located at #{restaurants.first.address} by #{catering_restaurants.find_by(restaurant_id: restaurants.first.id).pickup_time}\n\n
           #{restaurants.last.name} located at #{restaurants.last.address} by #{catering_restaurants.find_by(restaurant_id: restaurants.last.id).pickup_time}.\n\nOnce you have the food in the bag, text back PICKUP."
        admin_text = "#{drivers.first.name} is confirmed for #{delivery_time} delivery to #{user.office_name} from #{restaurants.first.name} and #{restaurants.last.name}."
      else
        driver_text = "Thanks for confirming your availability. For today's delivery, you'll be picking up from #{restaurants.first.name} located at #{restaurants.first.address} by #{catering_restaurants.find_by(restaurant_id: restaurants.first.id).pickup_time}.\n\nOnce you have the food in the bag, text back PICKUP."
        admin_text = "#{drivers.first.name} is confirmed for #{delivery_time} delivery to #{user.office_name} from #{restaurants.first.name}."
      end

      self.update_attribute("notify_driver", true)
      send_message("6041234567", admin_text)
      send_message(drivers.first.phone, driver_text)
    else # NO CANT DELIVER
      restaurants = Restaurant.find(subselections.pluck(:restaurant_id).uniq)
      if restaurants.count >= 2
        admin_text = "#{drivers.first.name}, #{drivers.first.phone} is not able to fulfill delivery for #{delivery_time} to #{user.office_name} from #{restaurants.first.name} and #{restaurants.last.name}."
      else
        admin_text = "#{drivers.first.name}, #{drivers.first.phone} is not able to fulfill delivery for #{delivery_time} to #{user.office_name} from #{restaurants.first.name}."
      end
      driver_text = "We appreciate the update. In the future, please let us know at least 48+ hours in advance if you cannot fulfill a delivery."

      self.update_attribute("notify_driver", true)
      send_message("6041234567", admin_text)
      send_message(drivers.first.phone, driver_text)
    end
  end

  def no_response_driver
    driver_text = "Hmm.. we didn't hear back from you for today's scheduled delivery. Please contact an admin ASAP to resolve this issue."
    admin_text = "NO RESPONSE - #{drivers.first.name}, #{drivers.first.phone} did not respond to confirmation SMS."
    self.update_attribute("notify_driver", true)
    send_message(drivers.first.phone, driver_text)
    send_message("6041234567", admin_text)
  end

  def calculate_total
    subtotal = catering_dishes.map do |catering_dish|
      quantity = catering_dish.quantity
      cost = dollars_to_cents(catering_dish.subselection.price)
      (quantity * cost)
    end
    subtotal = subtotal.sum
    delivery_fee = dollars_to_cents(20)
    tax = (subtotal + delivery_fee) * 0.05
    total = (subtotal + delivery_fee + tax).round
    {total: total, tax: tax, subtotal: subtotal, delivery_fee: delivery_fee}
  end

  private

  def send_message(phone_number, alert_message)
    @twilio_number = ENV['TWILIO_FROM_NUMBER']
    client = Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
    message = {
      to: phone_number,
      body: alert_message,
      messaging_service_sid: ENV['TWILIO_COPILOT_SID']
    }
    client.messages.create(message)
  end

  def dollars_to_cents(dollars)
    (100 * dollars.to_r).to_i
  end
end

app/controllers/catering_orders_controller.rb
class CateringOrdersController < ApplicationController
  layout "main"
  def index
    if current_user.present?
      @user_orders = current_user.catering_orders.where(:preauthorized => true).order(created_at: :desc)
    else
      redirect_to '/dashboard'
    end
  end
  def show
    # #crappy user auth
    # #change to current_user == user.id
    # if current_user.present?
    #   redirect_to '/dashboard'
    # end
    @order = CateringOrder.find(params[:id])
    @invoice = Stripe::Invoice.retrieve(@order.stripe_invoice_id)
    @catering_dishes = @order.catering_dishes
  end
  def cancel_request
    @order = CateringOrder.find(params[:order])
    @order.update!({status: "cancellation_requested"})
    puts "Emailing admin for CANCEL ORDER REQUEST order: #{@order.id}"
    from_address = "Deliveryapp Support <support@deliveryapp.com>"
    subject = "Cancel Order Request"
    Pony.mail(
        :from => from_address,
        :to => ["support@deliveryapp.com","orders@deliveryapp.com","admin@deliveryapp.com"],
        :subject => "Deliveryapp Order CANCEL REQUEST",
        :html_body => ERB.new(File.read('app/views/user_mailer/admin_cancel.text.erb'),nil,'-').result(binding),
        :via => :smtp,
        :via_options => default_email_options)
    head :ok
  end
  def cancel_order
    # moved to AA controller
  end
end

app/views/catering_orders/index.html.erb
<div class="test" style="height:100px">
  <%= image_tag "banner_accent_v1.svg", :class => "jumbotron-accent", :height => '100px' %>
</div>
<div class="container" style="min-height:190vh">
  <div class="modal-dialog modalcard-orderhistory" role="document" >
    <div class="modal-content modalcard-orders">
      <button onclick="location.href='/dashboard'" type="button" class="btn-zest zest-close" aria-label="Go back" style="top:0px;right:-80px;"><span aria-hidden="true">←</span></button>

      <% if @user_orders.present? %>
        <% @user_orders.each do |order| %>
          <% if order.delivery_date.present? && order.delivery_date > Date.today #change to pending && not cancelled %>
            <div class="modal-header modalcard-header-orderhistory">
              <h3 class="modal-title modalcard-title">Upcoming Orders</h3>
            </div>
            <div class="modalcard-body">
              <div class="needs-validation cardform" id="card-form">
                <div class="modal-section">
                  <div class="modalcard-subtitle-date">
                    <%= order.delivery_date.strftime("%^B %-d, %Y") %>
                  </div>
                </div>
                <%= link_to catering_order_path(order.id) do %>
                  <div class="col-md-12">
                    <div class="order-listing">
                      <div class="col-lg-9 card-id" style="padding-left:35px">
                        <% a = 0 %>
                        <% CateringDish.where(:catering_order_id => order.id).each do |cdish| %>
                          <% a += 1 %>
                          <% if cdish.present? %>
                            <% if a > 1 %>
                              &
                            <% end %>
                            <%= cdish.subselection.dish.restaurant.name %>
                          <% end %>
                        <% end %>
                      </div>
                      <div class="col-lg-3" style="padding-right:50px">
                        <%= sprintf('$%0.2f', order.total_price.to_f / 100.0).gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1,") unless order.total_price.nil? %>
                        <div class="order-listing-caret">
                          <%= image_tag("caret.svg", class: "modalcard-check_icon", :alt => "Icon Arrow")%>
                        </div>
                        <%# order.status %>
                      </div>
                    </div>
                  </div>
                <% end %>
                <% if order.cancelled_at.present? %>
                  <div class="order-cancel-subtitle">This order was cancelled on <%= order.cancelled_at.strftime("%B %-d, %Y") %></div>
                <% elsif order.status == "cancellation_requested" %>
                  <div class="order-cancel-subtitle">This order is pending cancellation</div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
        <!--        <script>$('body').attr('style','margin-top: 0px; overflow-x:hidden'); //specific to orders page, aligns nav + footer-->
        <!--                $('.dashboardpage-body-container').attr('style','height:100%;');-->
        <!--        </script>-->
      <% else %>
        <div class="modal-header modalcard-header-orderhistory">
          <h3 class="modal-title modalcard-title">It doesn't look like you've ordered anything yet. <br> Once you place an order, you'll see it here.</h3>
        </div>
        <script>$('.dashboardpage-body').attr('style','margin-top: -20px;margin-bottom: -46px'); //specific to orders page, aligns nav + footer</script>
      <% end %>
      <% if @user_orders.present? %>
        <div class="modal-header modalcard-header-orderhistory modalcard-header-orderhistory-past">
          <h3 class="modal-title modalcard-title">Past Orders</h3>
        </div>
        <% @user_orders.each do |order| %>
          <% if order.delivery_date.present? && (order.delivery_date <= Date.today) %>
            <div class="modalcard-body">
              <div class="needs-validation cardform" id="card-form">
                <div class="modal-section">
                  <div class="modalcard-subtitle-date">
                    <%= order.delivery_date.strftime("%^B %-d, %Y") %>
                  </div>
                </div>
                <%= link_to catering_order_path(order.id) do %>
                  <div class="col-md-12">
                    <div class="order-listing">
                      <div class="col-lg-9 card-id" style="padding-left:35px">
                        <% a = 0 %>
                        <% CateringDish.where(:catering_order_id => order.id).each do |cdish| %>
                          <% if cdish.present? && cdish.subselection.present? %>
                            <% a += 1 %>
                            <% rname = Restaurant.where(:id => cdish.subselection.restaurant_id).last.name||= cdish.subselection.dish.restaurant.name %>
                            <% if a > 1 %>
                              &
                            <% end %>
                            <%= rname %>
                          <% end %>
                        <% end %>
                      </div>
                      <div class="col-lg-3" style="padding-right:50px">
                        <%= sprintf('$%0.2f', order.total_price.to_f / 100.0).gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1,") unless order.total_price.nil? %>
                        <div class="order-listing-caret">
                          <%= image_tag("caret.svg", class: "modalcard-check_icon", :alt => "Icon Arrow")%>
                        </div>
                        <%# order.status %>
                      </div>
                    </div>
                  </div>
                <% end %>
                <% if order.cancelled_at.present? %>
                  <div class="order-cancel-subtitle">This order was cancelled on <%= order.cancelled_at.strftime("%B %-d, %Y") %></div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <div id="hiddenField" data-restaurant-id="" data-dish-id="" style="visibility: hidden"></div>
    </div>
  </div>
</div>
<script>

    $dropdown = $(".dropdown > .dropdown-group");
    $dropdownToggle = $(".dropdown-toggle");
    $dropdownMenu = $(".dropdown-menu");
    showClass = "show";

    if (window.matchMedia("(min-width: 768px)").matches) {

        $dropdown.hover(
            function() {
                const $this = $(this);
                $this.addClass(showClass);
                $this.find($dropdownToggle).attr("aria-expanded", "true");
                $this.find($dropdownMenu).addClass(showClass);
            },
            function() {
                const $this = $(this);
                $this.removeClass(showClass);
                $this.find($dropdownToggle).attr("aria-expanded", "false");
                $this.find($dropdownMenu).removeClass(showClass);
            }
        );
    } else {
        $dropdown.off("mouseenter mouseleave");
    }
</script>