config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  post '/admin/catering_orders/cancel_order', to: 'admin/catering_orders#cancel_order', as: :admin_cancel_catering_order
  ActiveAdmin.routes(self)
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  root 'dashboard#catering'
  get 'phone', to: 'users#new', as: :signup_phone
  get 'verify', to: 'users#new', as: :signup_verify
  get 'profile', to: 'users#new', as: :signup_profile
  get 'location', to: 'users#new', as: :signup_location
  get 'new_apartment', to: 'users#no_apartment_found', as: :no_apartment_found
  get 'order_payment/:url_safe_token', to: 'users#order_payment', as: :order_payment

  post 'register_payment', to: 'users#register_payment', as: :register_payment
  get 'users/:id(.:format)', to: 'users#show', as: :user

  get 'thanks', to: 'users#thankyou', as: :thankyou
  get 'cc_complete', to: 'users#cc_complete', as: :cc_thankyou

  post 'api/v1/text_response', to: 'api/v1/text_response#receive'
  
  get 'orders', to: 'catering_orders#index'
  get 'orders/:id(.:format)', to: 'catering_orders#show', as: :catering_order
  post 'orders/cancel_order', to: 'catering_orders#cancel_order', as: :cancel_catering_order
  post 'orders/cancel_request', to: 'catering_orders#cancel_request', as: :cancel_catering_order_request
  get 'dashboard', to: 'dashboard#catering', as: :dashboard
  get 'dashboard/order_complete', to: 'dashboard#order_complete'
  get 'dashboard/order_history', to: 'dashboard#order_history'
  get 'newsletter_subscribers', to: 'dashboard#catering'
  post 'newsletter_subscribers', to: 'dashboard#create_newsletter_subscriber'
  post 'dashboard/update_filter_selections', to: 'dashboard#update_filter_selections'
  post 'dashboard/edit_catering_item', to: 'dashboard#edit_catering_item'
  post 'dashboard/check_payment_source', to: 'dashboard#check_payment_source'
  post 'dashboard/check_dish_minimum', to: 'dashboard#check_dish_minimum'
  post 'dashboard/bulk_update_catering_dishes', to: 'dashboard#bulk_update_catering_dishes'
  post 'dashboard/preauth_payment', to: 'dashboard#preauth_payment'
  post 'dashboard/place_catering_order', to: 'dashboard#place_catering_order'
  post 'dashboard/update_sms_number', to: 'dashboard#update_sms_number'
  post 'dashboard/reset_password', to: 'dashboard#reset_password'
  delete 'dashboard/delete_catering_dish', to: 'dashboard#delete_catering_dish'

  post 'dashboard/sign_up', to: 'dashboard_users#sign_up'
  post 'dashboard/login', to:'dashboard_users#login'
  get 'signup', to:'dashboard_users#new'
  get 'login', to:'dashboard_users#new_session'
  patch 'users/:id', to:'dashboard_users#update'

  get 'm/:url_safe_token', to: 'menus#show', as: :menu_image_redirect

  get ':slug', to: 'dashboard#catering', as: :restaurant
  resources 'pairings'

end

app/views/layouts/_dashboard_nav.html.erb
<div class="container" style="padding:8px">
  <nav class="navbar justify-content-between dashboardnav" style="height:73px">
    <%= link_to(image_tag("001logo.png", class: "navbar-brand navbar-w2p", width: "70", height:"50", :alt => "Deliveryapp Logo", :data => {}), dashboard_path) %>
    <ul class="navbar padb-0 mb-0" style="margin-right: 76px;margin-top: -12px;">
      <% if current_user %>
      <div class="dropdown show">
        <div class="dropdown-group">
          <div class="dropdown-user" id="dropdownMenuLink"  aria-haspopup="true" aria-expanded="false">
            <%# image_tag("user_avatar.svg", class: "dashboardnav-usericon", width: "30", height:"30") %>
            <%="Logged in as #{current_user.name}" %>
          </div>
          <div class="dropdown-menu dashboardnav-dropdown" aria-labelledby="dropdownMenuLink">
            <%= link_to "Account", user_path(current_user), :class => 'dropdown-item' %>
            <a href="/orders" id="order_history_link" class="dropdown-item">Order History</a>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
          </div>
        </div>
      </div>
      <% else %>
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
          <div class="btn-group mr-4" role="group" aria-label="First group">
            <a href="/signup" class="btn btn-outline-primary brand-button-outline my-2 my-sm-0 signupbtn" id="sign-up" type="submit">Sign Up</a>
          </div>
          <div class="btn-group mr-2" role="group" aria-label="First group">
            <a href="/login" class="btn btn-primary brand-button-primary my-2 my-sm-0 loginbtn" type="submit" id="login">Login</a>
          </div>
        </div>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/_jumbotron.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-main" id="background-photo">
  <%= render "layouts/jumbotron_address" %>
  <%= render "layouts/nav_dropdown" %>
  <a href="#" id="banner_event">
    <div class="jumbotron-banner" style="">
      <span class="jumbotron-banner-title"><span class="jumbotron-banner-icon">🎉</span> $0 delivery launch event</span>
      <span class="jumbotron-banner-link">LEARN MORE <span class="zest-fwd-arrow" style="top:0px">→</span></span>
    </div>
  </a>
</div>
<div class="test" style="position: absolute;height: 84px;width: 100%;/*! top: -83px; */margin-top: -83px;/*! background-color: white; */border-bottom: 83px solid white;border-right: 112vw solid transparent;">
  <%# image_tag "banner_accent_v1.svg", :class => "jumbotron-accent", :style => "width:100%;height:320px" %>
</div>

app/views/layouts/_jumbotron_address.html.erb
<div class="row" id="address" style="margin-top: 89px;position: relative;">
  <div class="col col-lg-12">
    <div class="jumbotron jumbotron-address">
      <h1 class="display-4 jumbotron-title">
        <div>
<!--          <div class="jumbotron-title_sub">-->
<!--            Deliver to-->
<!--          </div>-->
          <br>
          <div id="locationField">
            <input id="autocomplete"
                  <% addr = @catering_order.address ||= "" %>
                  <% if current_user %>
                    <% if current_user.office_address.present? %>
                      placeholder="<%= current_user.office_address %>"
                      value="<%= current_user.office_address %>"
                    <% else %>
                      placeholder="Where's your office located?"
                      value="<%= addr %>"
                    <% end %>
                  <% else %>
                    placeholder="Where's your office located?"
                    value="<%= nil %>"
                  <% end %>
                   type="text"/>
          </div>
        </div>
      </h1>
      <hr class="jumbotron-hr">
      <p class="lead jumbotron-lead">
        We currently serve Downtown Vancouver, East Vancouver, and Burnaby.
      </p>
    </div>
  </div>
</div>

app/views/layouts/_nav_dropdown.html.erb
<% date_selected = @date ? @date : 2.days.from_now.in_time_zone('Pacific Time (US & Canada)') %>

<div class="row" id="dropdown-row">
  <div class="dropdown-title">
    Choose a Date, Time, Budget & Dish type
  </div>
  <div class="col col-xs-12 col-sm-9 pl-0 navdropdown">
    <div class="dropdown dropdown-filters" style="min-width: 140%">
      <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownDate" data-target="#cateringDatePicker" data-catering-date=<%=time%> >
          <div
            class="input-group log-event"
            id="datetimepicker1"
            data-td-target-input="nearest"
            data-td-target-toggle="nearest"
          >
            <input
              id="datetimepicker1Input"
              type="text"
              class="form-control"
              data-td-target="#datetimepicker1"
            />
            <span
              class="input-group-text"
              data-td-target="#datetimepicker1"
              data-td-toggle="datetimepicker"
            >
              <%=image_tag("filter_calendar.svg", class: "dropdown-iconwrapper_icon_new2 dropdown-iconwrapper_icon", :alt => "Icon Calendar")%>
            </span>
          </div>
            
          
          <span id="cateringDate" data-date-selected=<%=date_selected.strftime("%d/%m/%Y")%>>
            <%= date_selected.strftime("%A, %B #{date_selected.to_time.day.ordinalize}") %>
          </span>
          <i class="dropdown-arrow"><%=image_tag("filter_dropdown_arrow.svg") %></i>
        </button>
      </div>

      <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle" id="dropdownTime" aria-haspopup="true">
          <div class="dropdown-iconwrapper">
            <%=image_tag("icon_time_v3.svg", class: "dropdown-iconwrapper_icon", :alt => "Icon Time")%>
          </div>
          <span id="time-content" data-time-selected="1">
            12:00 PM - 12:15 PM
          </span>
          <i class="dropdown-arrow"><%=image_tag("filter_dropdown_arrow.svg") %></i>
        </button>

        <div class="dropdown-menu dropdown-menufilters" aria-labelledby="dropdownTime">
          <li class="dropdown-item time-item" id="1"> 11:00 AM - 11:15 AM </li>
          <li class="dropdown-item time-item" id="2"> 11:15 AM - 11:30 AM </li>
          <li class="dropdown-item time-item" id="3"> 11:30 AM - 11:45 AM </li>
          <li class="dropdown-item time-item" id="4"> 11:45 AM - 12:00 PM </li>
          <li class="dropdown-item time-item" id="5"> 12:00 PM - 12:15 PM </li>
          <li class="dropdown-item time-item" id="6"> 12:15 PM - 12:30 PM </li>
          <li class="dropdown-item time-item" id="7"> 12:30 PM - 12:45 PM </li>
          <li class="dropdown-item time-item" id="8"> 12:45 PM - 1:00 PM </li>
          <li class="dropdown-item time-item" id="9"> 1:00 PM - 1:15 PM </li>
          <li class="dropdown-item time-item" id="10"> 1:15 PM - 1:30 PM </li>
          <li class="dropdown-item time-item" id="11"> 1:30 PM - 1:45 PM </li>
          <li class="dropdown-item time-item" id="11"> 1:45 PM - 2:00 PM </li>
          <li class="dropdown-item time-item" id="11"> 2:00 PM - 2:15 PM </li>
          <li class="dropdown-item time-item" id="11"> 2:15 PM - 2:30 PM </li>
          <li class="dropdown-item time-item" id="11"> 2:30 PM - 2:45 PM </li>
          <li class="dropdown-item time-item" id="11"> 2:45 PM - 3:00 PM </li>
        </div>
      </div>

      <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle" id="dropdownCost" aria-haspopup="true">
          <div class="dropdown-iconwrapper">
            <%=image_tag("icon_budget_v2.svg", class: "dropdown-iconwrapper_icon", :alt => "Icon Budget")%>
          </div>
          <span id="price-content" data-price-filter="9999">
            Budget per person
          </span>
          <i class="dropdown-arrow"><%=image_tag("filter_dropdown_arrow.svg") %></i>
        </button>
        <div class="dropdown-menu dropdown-menufilters" aria-labelledby="dropdownCost">
          <li class="dropdown-item price-item" data-price-filter="9999"> Show all </li>
          <li class="dropdown-item price-item" data-price-filter="10"> $10 and less </li>
          <li class="dropdown-item price-item" data-price-filter="12"> $12 and less </li>
          <li class="dropdown-item price-item" data-price-filter="15"> $15 and less </li>
          <li class="dropdown-item price-item" data-price-filter="20"> $20 and less </li>
        </div>
      </div>

      <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle" id="dropdownType" aria-haspopup="true">
          <div class="dropdown-iconwrapper">
            <%=image_tag("filter_dishtype.svg", class: "dropdown-iconwrapper_icon_new dropdown-iconwrapper_icon", :alt => "Icon Type")%>
          </div>
          <span id="type-content">
            Dish Types
          </span>
          <i class="dropdown-arrow"><%=image_tag("filter_dropdown_arrow.svg") %></i>
        </button>
        <div class="dropdown-menu dropdown-menufilters dropdown-menu-type" aria-labelledby="dropdownType">
          <form>
            <li class="dropdown-item type-item" data-dish-type="0"> <div class="select-icon"></div>Show All </li>
            <li class="dropdown-item type-item" data-dish-type="1"> <div class="select-icon"></div>Individually Packed </li>
            <li class="dropdown-item type-item" data-dish-type="2"> <div class="select-icon"></div>Sharing Platters </li>
            <li class="dropdown-item type-item" data-dish-type="3"> <div class="select-icon"></div>Gluten-free </li>
            <li class="dropdown-item type-item" data-dish-type="4"> <div class="select-icon"></div>Dairy-free </li>
            <li class="dropdown-item type-item" data-dish-type="5"> <div class="select-icon"></div>Vegan </li>
          </form>
        </div>
      </div>

    </div>
  </div>
  <div class="col col-xs-0 col-lg-3">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Testapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%# stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%# javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application" %>
    <script type="text/javascript">
    /*to prevent Firefox FOUC, this must be here*/
    let FF_FOUC_FIX;
    </script>
    <%= javascript_include_tag "application", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=0.9" />
  <title><%= content_for?(:title) ? yield(:title) : "Deliveryapp — Office Catering" %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag "fontawesome" %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <%= favicon_link_tag(source='favicon.png') %>

  <%= javascript_include_tag 'application', type: "module", defer: true %>
  
  
  <%= tag :meta, :name => "stripe-key", :content => Rails.application.credentials[:stripe_public_key] %>
  

  <!--<script async="async" src="https://js.stripe.com/v3/"></script>-->
  <%# javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  <script>
    /*to prevent Firefox FOUC, this must be here*/
    let FF_FOUC_FIX;
  </script>
  <!--<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>-->
</head>
<%= render "modals/loader_modal" %>
<!--FOUC fix (visibility:hidden, shows when ready)-->
<body style="margin-top:-22px;">
  <!--FOUC fix for FF-->
  <script>
    0
  </script>
  <div class="dashboardpage-body">
    <div class="dashboardpage-body-container">
      <div class="container-fluid cateringdashboard">
        <div class="nav-container" id="nav-container" style="position: absolute;background: white;width: 100%;margin-bottom: 100px;">
<!--        <div class="nav-container" id="nav-container" style="position: absolute;background: white;width: 100%;margin-bottom: 100px;" data: {'turbolinks-action': "replace"}>-->
          <%= render "layouts/dashboard_nav" %>
        </div>
<!--        <div style="min-height:95px"></div>-->
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
    <div class="dashboard-footer" style="font-size: 12px; color:white">
      <div class="footer-row" style="width: 1250px;justify-content: space-between;font-size: 1rem;">
        <div class="l1" style="font-family: SF-Pro-Display-Light; padding-left: 0px;line-height: 35px;letter-spacing: 0.2px">
          <div><%= link_to(image_tag("001logo.png", class: "", width: "120", height:"100", :alt => "Deliveryapp Logo"), dashboard_path) %></div>
        </div>
        <div class="l2" style="font-family: GothamMedium;padding-bottom: 12px;line-height: 34px;">
          <div class="dashboard-footer-header">PRIMARY PAGES</div>
          <div class="dashboard-footer-list">
            <ul>
              <li>Home</li>
              <li>What We Do</li>
              <li>About Us</li>
              <li></li>
            </ul>
          </div>
        </div>
        <div class="l3" style="font-family: GothamMedium;padding-bottom: 12px;line-height: 34px;">
          <div class="dashboard-footer-header">WORK WITH US</div>
          <div class="dashboard-footer-list">
            <ul>
              <li>Become a Restaurant</li>
              <li>Become a Driver</li>
              <li></li>
              <li></li>
            </ul>
          </div>
        </div>
        <div class="l4" style="font-family: GothamMedium;padding-bottom: 12px;line-height: 34px;">
          <div class="dashboard-footer-header">SUPPORT</div>
          <div class="dashboard-footer-list">
            <ul>
              <li>FAQ</li>
              <li>Privacy Policy</li>
              <li>Terms of Service</li>
              <li>Contact Us</li>
            </ul>
          </div>
        </div>
        <div class="l5" style="font-family: GothamMedium;padding-bottom: 12px;line-height: 34px;">
          <div class="dashboard-footer-header">SUBSCRIBE TO OUR NEWSLETTER</div>
          <div class="dashboard-footer-list">
            <ul style="line-height: 20px">
              <li style="width:312px; margin-top: 23px"><span>Get updates when we launch new restaurant</span> <span style="position: relative;top:0px;">partners and dish offerings. We'll never spam you.</span></li>
              <li style="height:24px"></li>
              <li>
                <%# form_for(@newsletter_subscriber, url: {:controller => "dashboard", :action => "create_newsletter_subscriber"}) do |f| %>
                  <%# f.text_field :email, required: true, :id => "newsletterEmail", placeholder: "Enter your email", style: "border:none;border-radius: 3px!important;height:36px;padding-left: 5px;" %>
                  <%# f.submit "Subscribe", :class => "btn btn-primary", :id => "newsletterSubscribe", style: "margin-left:10px" %>
                <%# end %>
<!--                <input type="text" placeholder="Enter your email" style="border:none;border-radius: 3px!important;height:36px;padding-left: 5px;">-->
<!--                <button class="btn btn-primary" style="margin-left:10px">Subscribe</button>-->
                <div class="invalid-feedback" id="newsletterEmailError">
                  Please provide a valid email.
                </div>
              </li>
              <li></li>
            </ul>
          </div>
        </div>
<!--        <hr style="width: 100%;background-color: #8698bf;height: 0px;">-->
        <div style="width:100%;display: flex;justify-content: space-between; border-top: 1px solid rgba(255, 255, 255, 0.18);margin-top: 42px;padding-top: 20px;">
          <div>
            <div style="font-size: 14px;padding-top: 14px;color: #8698bf;"><div style="font-family: SF-Pro-Display-Thin;display: inline;padding-right: 6px">©</div><%= Time.now.year %> Deliveryapp</div>
            <div style="font-size: 14px;color: #8698bf">Made with ♡ in Vancouver</div>
          </div>

          <div style="color:#8698bf;display: flex;align-items: center"><i class="fab fa-instagram fa-2x"></i></div>
        </div>
      </div>
    </div>
  </div>
  <%= render "modals/datepicker_modal" %>
  <%= render "modals/banner_modal" %>
  <div id="dishmodal-container"><%= render "modals/dish_modal", locals: {dish: @dish} %></div>
  <%# render "modals/signup_modal" %>
  <%# render "modals/login_modal" %>
  <%= render "modals/reset_password_modal" %>
  <%= render "modals/reset_pw_confirm_modal" %>
  <%= render "modals/restaurant_closed_modal" %>
  <%= render "modals/dish_minimum_modal" %>
  <%= render "modals/dish_none_added_modal" %>
  <%= render "modals/too_many_restaurants_modal" %>
  <%#= render 'modals/cancel_confirmation_modal' %>
  <% if current_user %>
    <div id="cardselect-container"><%= render "modals/card_select_modal", locals: {current_user: @current_user} %></div>
    <div id="payment-container"><%= render "modals/payment_modal" %></div>
    <div id="ordercomplete-container"><%= render "modals/order_complete_modal" %></div>
    <div id="review-container"><%= render "modals/review_summary_modal", locals: {catering_dishes: @catering_dishes} %></div>
  <% end %>
  <!--FOUC fix for JS free browsers-->
  <noscript><style>body { visibility: visible !important; }</style></noscript>
</body>
<!--<div class="col col-lg-2" id="summaryContainer" style="">-->
  <%#render "dashboard/summary", locals: {restaurant: @restaurant, catering_dishes: @catering_dishes} %>
<!--</div>-->
</html>